name: Cronjob
on: 
  schedule:
    - cron: '* * * * *' 

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Run python script
        run: python hello.py

